const gameplayTexts = {
	coinsButtonTexts: {
		title: 'Coins',
	},
	coinsTabTexts: {
		coinsAmountPt1: 'You have ',
		coinsAmountPt2: 'Coins.',
		getMore: 'Get More',
	},
	energyButtonTexts: {
		title: 'Energy',
	},
	energyTabTexts: {
		fullIn: 'Full Energy in:',
		rate: 'Rate: ',
		perHour: '/h',
		getMore: 'Get More',
	},
	actionsButtonTexts: {
		title: 'Actions',
	},
	characterInfoTexts: {
		title: 'Character Info',
	},
	disastersIconTexts: {
		title: 'Disaster',
	},
	craftingButtonTexts: {
		title: 'Crafting',
	},
	seenButtonTexts: {
		title: 'Seen',
	},
	zoomSliderTexts: {
		title: 'ZoomSlider',
	},
	mapCompassTexts: {
		title: 'MapCompass',
	},
	errorMessagesTexts: {
		invalidBrowser:
			'This Application is not supported for this browser, please try to open it using an up-to-date version of Google Chrome, Mozilla Firefox, or Microsoft Edge.',
		invalidComponentsToMount: 'please pass a string or an array of strings to either mountComponent() or unmountComponent()',
	},
	characterInfoWindow: {
		title: 'Character window',
		JoinedAt: 'Joined at: ',
		TimePlayed: 'Time played: ',
		ItemDiscovered: 'Item discovered: ',
		Achievments: 'Achievments: ',
		DisatsteresServived: 'Disatsteres servived: ',
		Health: 'Health: ',
		SleepDuration: 'Sleep duration avg: ',
		SleepQuality: 'Sleep quality: ',
		FoodQuality: 'Food quality: ',
		HeatTolerence: 'Heat tolerence: ',
		ColdTolerence: 'Cold tolerence: ',
		Memory: 'Memory: ',
		FuturePlanning: 'Future planning: ',
		Hours: ' hours',
		HouresADay: ' h/d',
		Tasks: ' tasks',
		ItemsTable: 'passive buffs',
	},
	itemsDetailes: {
		item: [
			'hammer gives you more strength and power',
			'axe',
			'fire',
			'd',
			'e',
			'f',
			'g',
			'h',
			'i',
			'j',
			'k',
			'l',
			'm',
			'n',
			'o',
			'p',
			'q',
			'r',
			's',
			't',
			'u',
			'v',
			'w',
			'x',
			'y',
			'z',
		],
	},
};
export default gameplayTexts;
export const {
	coinsButtonTexts,
	coinsTabTexts,
	energyButtonTexts,
	energyTabTexts,
	actionsButtonTexts,
	characterInfoTexts,
	disastersIconTexts,
	craftingButtonTexts,
	seenButtonTexts,
	zoomSliderTexts,
	mapCompassTexts,
	errorMessagesTexts,
	characterInfoWindow,
	itemsDetailes,
} = gameplayTexts;
